services:
  app:
    image: carloschungu/tads-project-laravel-app:amd64
    container_name: laravel-app
    restart: unless-stopped
    expose:
      - "9000"
    environment:
      - DB_HOST=db
      - DB_DATABASE=db_tads_docker
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
      - DB_PORT=3306
    volumes:
      - app_public:/var/www/public
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - app_public:/var/www/public
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db_tads_docker
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
  app_public:
